@startuml
title Warmhouse Monolith Context Diagram
top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "Пользователь системы")
Person(engineer, "Engineer", "Специалист по подключению")
System(WarmhouseSystem, "Warmhouse System", "Система управления датчиками, получение данных от датчиков")
System_Ext(sensor, "Sensor", "Датчик")

Rel(user, WarmhouseSystem, "Просматривает значения датчиков, управляет датчиками")
Rel(engineer, WarmhouseSystem, "Подключает/отключает датчики")
Rel(WarmhouseSystem, sensor, "Запрашивает данные с датчика, устанавливает значение/статус")
@enduml
